Sprint 1
Genexys/middle.messenger.praktikum.yandex pull request #1
Opened 2022-09-04 22:54 UTC by Genexys

2022-09-05 09:14 UTC, podlovchenko requested changes
Привет, в целом все хорошо, есть несколько замечаний
Поехала верстка
<img width="502" alt="Снимок экрана 2022-09-05 в 12 12 50" src="https://user-images.githubusercontent.com/22602747/188413740-b8da44c4-d6f6-4356-a426-3127ba8e2c42.png">
Нет ссылок на фигму и нетлифай в ридми

2022-09-05 09:14 UTC, podlovchenko commented on .eslintrc
> +}
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-09-05 09:14 UTC, podlovchenko commented on package.json
> +    "parcel": "^2.7.0",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-09-05 09:14 UTC, podlovchenko commented on src/components/button/index.pug
> +      type=args.type ? args.type : 'button'
Можно
```suggestion
      type=args.type ?? 'button'
```

2022-09-05 09:14 UTC, podlovchenko commented on src/components/contextMenu/contextMenu.scss
> +    span {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-09-05 19:13 UTC, Genexys commented on src/components/button/index.pug
> +      type=args.type ? args.type : 'button'
![image](https://user-images.githubusercontent.com/11525479/188504039-faf0e3c4-96de-45f7-a520-f227e7f283f8.png)
говорит нельзя(

2022-09-05 20:07 UTC, Genexys commented on .eslintrc
> +}
done

2022-09-05 20:07 UTC, Genexys commented on package.json
> +    "parcel": "^2.7.0",
done

2022-09-05 20:07 UTC, Genexys commented on src/components/contextMenu/contextMenu.scss
> +    span {
done

2022-09-06 15:17 UTC, podlovchenko requested changes
При открытии нетлифай
<img width="844" alt="Снимок экрана 2022-09-06 в 18 16 56" src="https://user-images.githubusercontent.com/22602747/188672620-19f8ffb6-ccfe-410f-8d2c-a271ef532ddf.png">

2022-09-07 07:35 UTC, podlovchenko commented
Привет)
Работу принимаю, но постарайся разобраться с версткой к следующему спринту
Сейчас у списка чатов почему-то есть скролл и можно прокрутить до такого состояния
<img width="655" alt="Снимок экрана 2022-09-07 в 10 32 44" src="https://user-images.githubusercontent.com/22602747/188817591-03920903-6f28-4116-87f8-63143e27b801.png">

2022-12-25 08:50 UTC, merged